#!/bin/bash

# ==========================================
# AIMAK VPS Nginx Setup (Without Plesk)
# ==========================================
# This script sets up Nginx for AIMAK on a VPS
# Run with: sudo bash setup-vps-nginx.sh
# ==========================================

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

# Configuration
DOMAIN="aimaqaqshamy.kz"
NGINX_CONF="/etc/nginx/sites-available/aimaqaqshamy"
NGINX_ENABLED="/etc/nginx/sites-enabled/aimaqaqshamy"
PROJECT_DIR="${PWD}"

# Functions
print_header() {
    echo ""
    echo -e "${BOLD}${CYAN}========================================${NC}"
    echo -e "${BOLD}${CYAN}$1${NC}"
    echo -e "${BOLD}${CYAN}========================================${NC}"
    echo ""
}

info() {
    echo -e "${GREEN}✓${NC} $1"
}

warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

error() {
    echo -e "${RED}✗${NC} $1"
}

step() {
    echo -e "${BLUE}▶${NC} ${BOLD}$1${NC}"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    error "Please run as root: sudo bash setup-vps-nginx.sh"
    exit 1
fi

print_header "AIMAK VPS Nginx Setup"

info "Domain: $DOMAIN"
info "Project: $PROJECT_DIR"
echo ""

# ==========================================
# Step 1: Check/Install Nginx
# ==========================================
print_header "Step 1: Checking Nginx"

if ! command -v nginx &> /dev/null; then
    warn "Nginx not found. Installing..."
    apt update
    apt install nginx -y
    info "Nginx installed successfully"
else
    info "Nginx is already installed: $(nginx -v 2>&1 | cut -d'/' -f2)"
fi

# Start nginx
systemctl start nginx
systemctl enable nginx
info "Nginx is running"

# ==========================================
# Step 2: Create Nginx Configuration
# ==========================================
print_header "Step 2: Creating Nginx Configuration"

step "Creating configuration file: $NGINX_CONF"

cat > $NGINX_CONF << 'NGINX_CONFIG_EOF'
# ==========================================
# Nginx Configuration for aimaqaqshamy.kz
# Generated by setup-vps-nginx.sh
# ==========================================

# Upstream definitions
upstream api_backend {
    server 127.0.0.1:4000;
    keepalive 64;
}

upstream web_frontend {
    server 127.0.0.1:3000;
    keepalive 64;
}

# HTTP server
server {
    listen 80;
    listen [::]:80;
    server_name aimaqaqshamy.kz www.aimaqaqshamy.kz;

    # Let's Encrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Logs
    access_log /var/log/nginx/aimaqaqshamy-access.log;
    error_log /var/log/nginx/aimaqaqshamy-error.log;

    # Max upload size
    client_max_body_size 10M;

    # API proxy
    location /api {
        proxy_pass http://api_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
        proxy_buffering off;
    }

    # WebSocket support
    location /socket.io {
        proxy_pass http://api_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
    }

    # Next.js static files
    location /_next/static {
        proxy_pass http://web_frontend;
        expires 365d;
        add_header Cache-Control "public, immutable";
    }

    # Next.js image optimization
    location /_next/image {
        proxy_pass http://web_frontend;
        proxy_cache_valid 200 30d;
    }

    # Main Next.js application
    location / {
        proxy_pass http://web_frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
        proxy_buffering off;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Hide nginx version
    server_tokens off;
}

# HTTPS server (will be configured by certbot)
NGINX_CONFIG_EOF

info "Configuration file created"

# ==========================================
# Step 3: Enable Configuration
# ==========================================
print_header "Step 3: Enabling Configuration"

# Remove default config if exists
if [ -f "/etc/nginx/sites-enabled/default" ]; then
    step "Removing default nginx configuration..."
    rm -f /etc/nginx/sites-enabled/default
    info "Default configuration removed"
fi

# Create symlink
if [ -L "$NGINX_ENABLED" ]; then
    step "Configuration already enabled"
else
    step "Creating symlink..."
    ln -s $NGINX_CONF $NGINX_ENABLED
    info "Configuration enabled"
fi

# ==========================================
# Step 4: Test Configuration
# ==========================================
print_header "Step 4: Testing Configuration"

step "Testing nginx configuration..."
if nginx -t 2>&1 | grep -q "successful"; then
    info "Nginx configuration is valid"
else
    error "Nginx configuration has errors!"
    nginx -t
    exit 1
fi

# ==========================================
# Step 5: Create Certbot Directory
# ==========================================
print_header "Step 5: Preparing for SSL"

step "Creating certbot directory..."
mkdir -p /var/www/certbot
chown -R www-data:www-data /var/www/certbot
info "Certbot directory created"

# ==========================================
# Step 6: Restart Nginx
# ==========================================
print_header "Step 6: Restarting Nginx"

step "Restarting nginx service..."
systemctl restart nginx
info "Nginx restarted successfully"

# ==========================================
# Step 7: Check Firewall
# ==========================================
print_header "Step 7: Checking Firewall"

if command -v ufw &> /dev/null; then
    step "Checking UFW firewall..."

    if ufw status | grep -q "Status: active"; then
        warn "UFW is active. Checking ports..."

        if ! ufw status | grep -q "80/tcp"; then
            step "Allowing HTTP (port 80)..."
            ufw allow 80/tcp
            info "HTTP port opened"
        else
            info "HTTP port already open"
        fi

        if ! ufw status | grep -q "443/tcp"; then
            step "Allowing HTTPS (port 443)..."
            ufw allow 443/tcp
            info "HTTPS port opened"
        else
            info "HTTPS port already open"
        fi
    else
        info "UFW is not active"
    fi
else
    info "UFW not installed (firewall check skipped)"
fi

# ==========================================
# Success Message
# ==========================================
print_header "Setup Complete!"

info "Nginx has been successfully configured!"
echo ""
echo -e "${BOLD}${CYAN}Next steps:${NC}"
echo ""
echo "1. ${BOLD}Verify DNS is configured:${NC}"
echo "   nslookup $DOMAIN"
echo "   (Should return: 82.115.49.251)"
echo ""
echo "2. ${BOLD}Check PM2 is running:${NC}"
echo "   pm2 status"
echo "   (Both aimak-api and aimak-web should be 'online')"
echo ""
echo "3. ${BOLD}Test the website:${NC}"
echo "   curl -I http://$DOMAIN"
echo "   (Should return HTTP 200)"
echo ""
echo "4. ${BOLD}Install SSL certificate:${NC}"
echo "   ${CYAN}sudo certbot --nginx -d $DOMAIN -d www.$DOMAIN${NC}"
echo ""
echo "5. ${BOLD}Verify HTTPS works:${NC}"
echo "   curl -I https://$DOMAIN"
echo ""

echo -e "${YELLOW}⚠  Important:${NC}"
echo "   - Make sure DNS is configured before installing SSL"
echo "   - Make sure PM2 applications are running"
echo "   - SSL installation will automatically update nginx config"
echo ""

print_header "Configuration Summary"

echo "Nginx config:     $NGINX_CONF"
echo "Nginx enabled:    $NGINX_ENABLED"
echo "Access log:       /var/log/nginx/aimaqaqshamy-access.log"
echo "Error log:        /var/log/nginx/aimaqaqshamy-error.log"
echo "Certbot dir:      /var/www/certbot"
echo ""

info "Setup completed successfully!"
echo ""
echo -e "${CYAN}For troubleshooting, see: VPS_SETUP_GUIDE.md${NC}"
echo ""
